klubvino/chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('chat', views.ChatView.as_view(), name='chat'),
]

klubvino/event_calendar/urls.py
from django.urls import path
from event_calendar import views

app_name = 'event_calendar'

urlpatterns = [
    path('events', views.EventMainView.as_view(), name='events'),
    path('event_detail/<int:pk>', views.EventInfoView.as_view(), name='event_detail'),
    path('create_event/', views.EventCreateView.as_view(), name='create_event'),
    path('update_event/<int:pk>', views.EventUpdateView.as_view(), name='update_event'),
    path('delete_event/<int:pk>', views.EventDeleteView.as_view(), name='delete_event'),
]

klubvino/klubvino/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views
from klubvino import settings

urlpatterns = [
    path('bestuur/admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('wineinfo/', include('wineinfo.urls', namespace='wineinfo')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('search/', include('search.urls', namespace='search')),
    path('events/', include('event_calendar.urls', namespace='event_calendar')),
    path('tasting/', include('winetasting.urls', namespace='winetasting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

klubvino/event_calendar/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class EventEntry(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField()
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, default="")
    last_update_by = models.CharField(max_length=100, default="", blank=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event_calendar:events")


    class Meta:
        ordering = ('-date', )

klubvino/event_calendar/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, View
from event_calendar.models import EventEntry
from django.urls import reverse_lazy
from django.contrib.auth.models import Permission, User
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.template.loader import render_to_string, get_template

# Create your views here.
class EventMainView(View):

    def get(self, request, *args, **kwargs):
        event_list = EventEntry.objects.all()
        return render(request, 'event_calendar/event_page.html', {'event_list':event_list})

class EventInfoView(DetailView):
    context_object_name = 'entry_detail'
    model = EventEntry
    template_name = 'event_calendar/event_detail.html'

class EventCreateView(CreateView):
    fields = "__all__"
    model = EventEntry

    def get_initial(self):
        initial = super(EventCreateView, self).get_initial()
        initial.update({'created_by': self.request.user.username})
        initial.update({'last_update_by': self.request.user.username})
        return initial

    def form_valid(self, form):
        self.object = form.save()
        email_body = get_template('event_calendar/_mail.html').render({
            'Title': self.object.name,
            'Date': self.object.date,
            'Description': self.object.description,
            'Author': self.object.created_by
        })
        user_list = User.objects.all()
        email_list = []
        for items in user_list:
            if items.email != '':
                email_list.append(items.email)
        msg = EmailMessage('Klub-Vino: Gebeure', email_body, 'mail@klub-vino.co.za', email_list)
        msg.content_subtype = 'html'
        msg.send(fail_silently=True)
        return redirect('event_calendar:events')


class EventUpdateView(UpdateView):
    fields = "__all__"
    model = EventEntry

    def get_initial(self):
        initial = super(EventUpdateView, self).get_initial()
        initial.update({'last_update_by': self.request.user.username})
        return initial


class EventDeleteView(DeleteView):
    model = EventEntry
    success_url = reverse_lazy('event_calendar:events')

klubvino/event_calendar/templates/event_calendar/_event_entry.html
{% for events in event_list.all %}
<div class="calendar_entry col-lg-3">
  <h3 class="calendar_name">{{ events.name }}</h3>
  <hr>
  <h4 class="calendar_date">{{ events.date|date:"D d M Y" }}</h4>
  <p>
    {{ events.description|truncatechars:30 }}
  </p>
  <button onclick="window.location='{% url 'event_calendar:event_detail' pk=events.id %}'" type="button" class="btn btn-primary calendar_button">Meer Inligting</button>
  <p></p>
</div>
{% endfor%}

klubvino/event_calendar/templates/event_calendar/_mail.html
<div style="background-color: rgba(48, 48, 48, .7); margin-left: 20px; margin-right: 20px">
  <h3 style="color: yellow; margin-left: 20px">{{ Title }}</h3>
  <hr>
  <h4 style="color: red; margin-left: 20px">{{ Date }}</h4>
  <p style="color: white; margin-left: 20px">{{ Description }}</p>
  <p style="font-size: 12px; margin-left: 20px; color: #42e5f4">Skrywer: {{ Author }}</p>
  <p style="margin-left: 20px; color: white">www.klub-vino.co.za/events/events</p>
</div>

klubvino/event_calendar/templates/event_calendar/event_detail.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h3 class="calendar_name">{{ entry_detail.name }}</h3>
      <hr>
      <h4 class="calendar_date">{{ entry_detail.date }}</h4>
      <p id="calendar_description">{{ entry_detail.description }}</p>
      <p id="calendar_created">Datum: {{ entry_detail.created }}</p>
      <p id="calendar_created">Skrywer: {{entry_detail.created_by }}</p>
      <p id="calendar_created">Dateer: {{entry_detail.last_update_by }}</p>
      <button onclick="window.location='{% url 'event_calendar:events' %}'" id="event_button" class="btn btn-primary glyphicon glyphicon-step-backward" type="button"> Terug</button>
      <a href="{% url 'event_calendar:update_event' pk=entry_detail.pk %}" id="event_button" class="btn btn-warning glyphicon glyphicon-edit" role="button"> Opdateer</a>
      <a href="{% url 'event_calendar:delete_event' pk=entry_detail.pk %}" id="event_button" class="btn btn-danger glyphicon glyphicon-remove" role="button"> Verwyder</a>
    </div>
  </div>
  <script src="{% static "JS/gebeure.js" %}"></script>
  {% endblock %}

klubvino/event_calendar/templates/event_calendar/event_page.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <button onclick="window.location='{% url 'event_calendar:create_event' %}'"type="button" class="btn btn-warning glyphicon glyphicon-plus event"> Nuwe</button>
    <div class="row">
      {% include 'event_calendar/_event_entry.html' %}
    </div>
  </div>
  <script src="{% static "JS/gebeure.js" %}"></script>
  {% endblock %}

klubvino/event_calendar/templates/event_calendar/evententry_confirm_delete.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h2>Gebeure</h2>
      <h2>Verwyder "{{evententry.name}}" op {{evententry.date}} van die kalender?:</h2>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Verwyder">
        <a href="{% url 'event_calendar:events' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Kanselleer</a>
      </form>
    </div>
  </div>
  <script src="{% static "JS/gebeure.js" %}"></script>
  {% endblock %}

klubvino/event_calendar/templates/event_calendar/evententry_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% load widget_tweaks %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form method="POST">
        {% csrf_token %}
        <p id="registrationform">Naam: {{form.name}}</p>
        <p id="registrationform">Datum en Tyd: {{form.date}}</p>
        <p id="registrationform">Beskrywing:</p>
        {{form.description|add_class:"form-control"}}
        <p></p>
        <p id="registrationform">Skrywer: {{form.created_by}}</p>
        <p id="registrationform">Dateer deur: {{form.last_update_by}}</p>
        <hr>
        <input type="submit" class="btn btn-warning glyphicon glyphicon-plus" value=" Laai Gebeur">
        <a href="{% url 'event_calendar:events' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Kanselleer</a>
      </form>
    </div>
  </div>
  <script src="{% static "JS/gebeure.js" %}"></script>
  {% endblock %}