klubvino/chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('chat', views.ChatView.as_view(), name='chat'),
]

klubvino/klubvino/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views
from klubvino import settings

urlpatterns = [
    path('bestuur/admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('wineinfo/', include('wineinfo.urls', namespace='wineinfo')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('search/', include('search.urls', namespace='search')),
    path('events/', include('event_calendar.urls', namespace='event_calendar')),
    path('tasting/', include('winetasting.urls', namespace='winetasting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

klubvino/winetasting/urls.py
from django.urls import path
from winetasting import views

app_name = 'winetasting'

urlpatterns = [
    path('tasting/', views.TastingMainView.as_view(), name='tasting'),
    path('create_tasting/', views.TastingCreateView.as_view(), name='create_tasting'),
    path('update_tasting/<int:pk>', views.TastingUpdateView.as_view(), name='update_tasting'),
    path('tasting/<int:pk>', views.WineTastingDetailView.as_view(), name='detail'),
    path('mystery_wine/', views.MysteryWineCreateView.as_view(), name='mystery_wine'),
    path('mystery_update/<int:pk>', views.MysteryWineUpdateView.as_view(), name='mystery_update'),
    path('results/', views.ResultView.as_view(), name='results'),
    path('results/<int:pk>', views.ResultUpdateView.as_view(), name='result_update'),
]

klubvino/winetasting/models.py
from django.db import models
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your models here.

class WineTasting(models.Model):

    date = models.DateTimeField()
    hosted_by = models.CharField(max_length=250)
    cultivar = models.CharField(max_length=250)
    location = models.CharField(max_length=250, default='')
    qty_wines = models.IntegerField()
    created_by = models.CharField(max_length=256, default='')
    close_tasting = models.BooleanField(default=False)


    def __str__(self):
        return '{}, {}'.format(str(self.date), self.location)

    def get_absolute_url(self):
        return reverse("winetasting:tasting")

    class Meta:
        ordering = ('date',)

class WineTastingInfo(models.Model):

    date = models.ForeignKey(WineTasting, related_name='proe_wyn', on_delete=models.CASCADE)
    cultivar = models.CharField(max_length=250)
    username = models.CharField(max_length=250)
    wine_code_name = models.CharField(max_length=10)
    points = models.DecimalField(decimal_places=2, max_digits=4, blank=True, default=0)
    comments = models.TextField(blank=True)

    def __str__(self):
        return '{}, {}, {}'.format(str(self.date), self.wine_code_name, self.username)

    def get_absolute_url(self):
        return reverse("winetasting:detail",kwargs={'pk':self.date.id})

    class Meta:
        ordering = ('wine_code_name', )

class WineTastingResults(models.Model):

    relative_date = models.DateTimeField(blank=True, null=True)
    cultivar = models.CharField(max_length=256)
    wine_code_name = models.CharField(max_length=256)
    pics = models.ImageField(upload_to='wine_pics', blank=True, null=True)
    real_name = models.CharField(max_length=256)
    cellar = models.CharField(max_length=256)
    year = models.IntegerField(blank=True, null=True)
    price = models.CharField(max_length=256)
    total = models.DecimalField(decimal_places=2, max_digits=4)

    def __str__(self):
        return self.wine_code_name

    def get_absolute_url(self):
        return reverse("winetasting:tasting")

    class Meta:
        ordering = ('-total', )

klubvino/winetasting/forms.py
from django import forms
from winetasting.models import WineTastingInfo
from django.contrib.auth.models import User


class WineTastingInfoForm(forms.ModelForm):

    class Meta():
        model = WineTastingInfo
        fields = '__all__'

klubvino/winetasting/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, View
from winetasting.models import WineTasting, WineTastingInfo, WineTastingResults
from winetasting.forms import WineTastingInfoForm
from wineinfo.models import Cultivar, WineInfo
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import Permission, User
from django.utils.dateparse import parse_datetime

# Create your views here.

class TastingMainView(View):

    def get(self, request, *args, **kwargs):
        tasting_list = WineTasting.objects.all()
        return render(request, 'winetasting/winetasting_page.html', {'tasting_list':tasting_list})

class WineTastingDetailView(DetailView):
    context_object_name = 'proe_goed'
    model = WineTasting
    template_name = 'winetasting/tasting_detail.html'

    def get_context_data(self, **kwargs):
        context = super(WineTastingDetailView, self).get_context_data(**kwargs)
        chk_date = context['proe_goed'].pk
        chk_closed = context['proe_goed'].close_tasting
        chk_list = WineTastingInfo.objects.filter(date=chk_date)
        if len(chk_list) != 0:
            context['result_btn'] = True
        else:
            context['result_btn'] = False
        return context

class TastingCreateView(CreateView):
    fields = "__all__"
    model = WineTasting

    def get_context_data(self, **kwargs):
        context = super(TastingCreateView, self).get_context_data(**kwargs)
        context['creating'] = True
        context['closing'] = False
        return context

    def get_initial(self):
        initial = super(TastingCreateView, self).get_initial()
        initial.update({'created_by': self.request.user.username})
        return initial


class TastingUpdateView(UpdateView):
    fields = ('close_tasting', )
    model = WineTasting

    def get_context_data(self, **kwargs):
        context = super(TastingUpdateView, self).get_context_data(**kwargs)
        context['creating'] = False
        context['closing'] = True
        return context

class MysteryWineCreateView(CreateView):
    fields = '__all__'
    model = WineTastingInfo

    def get_initial(self):
        initial = super(MysteryWineCreateView, self).get_initial()
        mySearch = self.request.GET['search']
        header_info = WineTasting.objects.filter(id=mySearch)
        for items in header_info:
            initial.update({'date': items.id})
            initial.update({'cultivar': items.cultivar})
        initial.update({'username': self.request.user.username})
        return initial

    # success_url = redirect('tasting:tasting', pk=7)

class MysteryWineUpdateView(UpdateView):
    fields = "__all__"
    model = WineTastingInfo

class MysteryWineDeleteView(DeleteView):
    model = WineTastingInfo
    success_url = reverse_lazy('winetasting:tasting')

class ResultView(View):

    def get(self, request, *args, **kwargs):
        mySearch = request.GET['results']
        header_info = WineTasting.objects.filter(id=mySearch)
        users_name = request.user.username
        result_header = WineTasting()
        code_names = []
        import string
        for letters in string.ascii_uppercase:
            code_names.append(letters)
        for items in header_info:
            result_header.cultivar = items.cultivar
            result_header.date = items.date
            result_header.location = items.location
            result_header.close_tasting = items.close_tasting
            result_header.created_by = items.created_by
            result_header.pk = items.pk
            number_of_wines = items.qty_wines
        body_info = []
        for items in range(0,number_of_wines):
            body_info.append(WineTastingInfo.objects.filter(date_id=mySearch, wine_code_name=code_names[items]))
        results_date = str(body_info[0][0].date).split(',')
        results_date = results_date[0]
        old_data = WineTastingResults.objects.filter(relative_date=results_date)
        save_object_data = {}
        if len(old_data) != 0:
            for items in old_data:
                save_object_data[str(items.wine_code_name)] = [items.real_name, items.cellar, items.price, items.pics, items.year]
            WineTastingResults.objects.filter(relative_date=results_date).delete()
        for stuff in range(0, len(body_info)):
            if len(body_info[stuff]) != 0:
                subtotal = 0
                number_of_votes = 0
                number_of_items = 0
                update_results = WineTastingResults()
                for items in range(0,len(body_info[stuff])):
                    number_of_votes += 1
                    subtotal += body_info[stuff][items].points
                    number_of_items += 1
                total = (subtotal/number_of_votes)
                date_unmod = str(body_info[stuff][items].date).split(',')
                date_mod = date_unmod[0]
                update_results.relative_date = date_mod
                update_results.cultivar = body_info[stuff][items].cultivar
                update_results.wine_code_name = body_info[stuff][items].wine_code_name
                update_results.total = total
                if body_info[stuff][items].wine_code_name in save_object_data:
                    update_results.real_name = save_object_data[body_info[stuff][items].wine_code_name][0]
                    update_results.cellar = save_object_data[body_info[stuff][items].wine_code_name][1]
                    update_results.price = save_object_data[body_info[stuff][items].wine_code_name][2]
                    update_results.pics = save_object_data[body_info[stuff][items].wine_code_name][3]
                    update_results.year = save_object_data[body_info[stuff][items].wine_code_name][4]
                update_results.save()
        if len(body_info) != 0:
            display_results = WineTastingResults.objects.filter(relative_date=results_date)
        return render(request, 'winetasting/results.html', {'result_header': result_header, 'display_results': display_results})

    def post(self, request, *args, **kwargs):
        relative_dt = request.POST.get('date')
        wines_to_save = WineTastingResults.objects.filter(relative_date=relative_dt)
        for items in wines_to_save:
            cultivar_name = items.cultivar
        chk_cultivar = Cultivar.objects.filter(name=cultivar_name).exists()
        if not chk_cultivar:
            save_cultivar = Cultivar()
            save_cultivar.name = cultivar_name
            save_cultivar.save()
        create_cultivar = Cultivar.objects.get(name=cultivar_name)
        for wines in wines_to_save:
            save_wine = WineInfo()
            chk_wine = WineInfo.objects.filter(cultivar=create_cultivar, cellar=wines.cellar, year=wines.year).exists()
            if not chk_wine:
                #create_cultivar = Cultivar.objects.get(name=cultivar_name)
                save_wine.cultivar = create_cultivar
                save_wine.name = wines.real_name
                save_wine.cellar = wines.cellar
                save_wine.year = wines.year
                save_wine.price = wines.price
                save_wine.rating = wines.total
                save_wine.pics = wines.pics
                save_wine.save()

        tasting_list = WineTasting.objects.all()
        return redirect('wineinfo:detail', pk=create_cultivar.id)

class ResultUpdateView(UpdateView):
    fields = '__all__'
    model = WineTastingResults

klubvino/winetasting/templates/winetasting/_tasting_entry.html
{% for tasting in tasting_list.all %}
<div class="calendar_entry col-lg-3">
  <h3 class="calendar_name">Wynproe: {{ tasting.cultivar }}</h3>
  <h3 id="tasting_location">Te: {{ tasting.location }}</h3>
  <hr>
  <h4 class="calendar_date">{{ tasting.date|date:"D d M Y" }}</h4>
  <p id="tasting_created">Aangebied deur: {{ tasting.hosted_by }}</p>
  <p></p>
  <a class="btn btn-primary glyphicon glyphicon-glass calendar_button" href="{{tasting.id}}"> Gaan Proe</a>
  {# <button onclick="window.location='{% url 'winetasting:tasting' pk=tasting.id %}'"type="button" class="btn btn-warning glyphicon glyphicon-plus event"> Nuwe</button> #}
</div>
{% endfor%}

klubvino/winetasting/templates/winetasting/results.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% load widget_tweaks %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h3 class="calendar_name">{{ result_header.cultivar }} - Resultate</h3>
      <h4 class="calendar_date">{{ result_header.date }}</h4>
      <h4 id="tasting_location">{{ result_header.location }}</h4>
      <hr>
      {% for wines in display_results %}
        {% if forloop.counter0 == 0 %}
          <button id="wyneproe_kode" class="btn-gold btn glyphicon glyphicon-king"> {{wines.wine_code_name}}</button>
        {% endif %}
        {% if forloop.counter0 == 1 %}
          <button id="wyneproe_kode" class="btn-silver btn glyphicon glyphicon-queen"> {{wines.wine_code_name}}</button>
        {% endif %}
        {% if forloop.counter0 == 2 %}
          <button id="wyneproe_kode" class="btn-bronze btn glyphicon glyphicon-tower"> {{wines.wine_code_name}}</button>
        {% endif %}
        {% if forloop.counter0 == 3 %}
          <button id="wyneproe_kode" class="btn btn-green glyphicon glyphicon-knight"> {{wines.wine_code_name}}</button>
        {% endif %}
        {% if forloop.counter0 == 4 %}
          <button id="wyneproe_kode" class="btn btn-blood glyphicon glyphicon-bishop"> {{wines.wine_code_name}}</button>
        {% endif %}
        {% if forloop.counter0 > 4 %}
          <button id="wyneproe_kode" class="btn btn-info glyphicon glyphicon-pawn"> {{wines.wine_code_name}}</button>
        {% endif %}
        {% if result_header.close_tasting %}
          {% if wines.pics%}
            <p></p>
            <img src="{{ wines.pics.url }}" alt="no image" width="200" height="300">
          {% else %}
            <p>Geen Kiekie!</p>
          {% endif %}
          <p></p>
          <p id="registrationform">Wyn naam: {{wines.real_name}}</p>
          <p id="registrationform">Kelder: {{wines.cellar}}</p>
          <p id="registrationform">Jaar: {{wines.year}}</p>
          <p id="registrationform">Prys: {{wines.price}}</p>
        {% endif %}
        <p id="results_point" class="calendar_name">Totale punt: {{wines.total}}/10</p>
        {% if user.username == result_header.created_by and not result_header.close_tasting %}
          <a href="{% url 'winetasting:result_update' pk=wines.pk %}" class="btn btn-warning glyphicon glyphicon-edit" role="button"> Opdateer</a>
        {% endif %}
        <hr>
      {% endfor %}
      <button onclick="goBack()" class="btn btn-primary glyphicon glyphicon-step-backward"> Terug</button>
      {% if user.username == result_header.created_by %}
        <p></p>
        <a href="{% url 'winetasting:update_tasting' pk=result_header.pk %}" class="btn btn-danger glyphicon glyphicon-lock" role="button"> Sluit-af</a>
      {% endif %}
      <p></p>
      {% if user.username == result_header.created_by and result_header.close_tasting %}
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
          <input type="hidden" name="date" value="{{ result_header.date|date:"Y-m-d H:i:s" }}">
          <button class="btn btn-green glyphicon glyphicon-save" type="submit"> Stoor resultate</button>
      </form>
      {% endif %}
    </div>
  </div>
  <script>
    function goBack(){
      window.history.back();
    }
  </script>
  <script src="{% static "JS/tasting.js" %}"></script>
  {% endblock %}

klubvino/winetasting/templates/winetasting/tasting_detail.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h3 class="calendar_name">{{ proe_goed.cultivar }}</h3>
      <h4 class="calendar_date">{{ proe_goed.date }}</h4>
      <h4 id="tasting_location">{{ proe_goed.location }}</h4>
      <hr>
      {% for wyne in proe_goed.proe_wyn.all %}
        <button id="wyneproe_kode" class="btn btn-primary">{{wyne.wine_code_name}}</button>
        <p id="registrationform">Kubernaam: {{wyne.username}}</p>
        <p id="registrationform">Kommentaar: {{wyne.comments}}</p>
        <p id="registrationform">Punt: {{wyne.points}}/10</p>
        {% if user.username == wyne.username and not proe_goed.close_tasting %}
          <a href="{% url 'winetasting:mystery_update' pk=wyne.pk %}" class="btn btn-warning glyphicon glyphicon-edit" role="button"> Opdateer</a>
        {% endif %}
        <p></p>
        <hr>
      {% endfor %}
      {% if not proe_goed.close_tasting %}
      <form action="{% url 'winetasting:mystery_wine' %}" method="GET">
        <input type="hidden" value="{{ proe_goed.id }}" name="search">
        <button class="btn btn-warning calendar_button" type="submit"><i class="glyphicon glyphicon-plus"> Nuwe Wyn</i></button>
      </form>
      {% endif %}
      {% if result_btn %}
        <form action="{% url 'winetasting:results' %}" method="GET">
          <input type="hidden" value="{{ proe_goed.id }}" name="results">
          <button class="btn btn-danger calendar_button" type="submit"><i class="glyphicon glyphicon-king"> Resultate</i></button>
        </form>
      {% endif %}
      <a href="{% url 'winetasting:tasting' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Terug</a>
    </div>
  </div>
  <script src="{% static "JS/tasting.js" %}"></script>
  {% endblock %}

klubvino/winetasting/templates/winetasting/winetasting_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form method="POST">
        {% csrf_token %}
        {% if creating %}
          <p id="registrationform">Datum en Tyd: {{form.date}}</p>
          <p id="registrationform">Aanbieding deur: {{form.hosted_by}}</p>
          <p id="registrationform">Kultivar: {{form.cultivar}}</p>
          <p id="registrationform">Plek: {{form.location}}</p>
          <p id="registrationform">Hoeveelheid wyne: {{form.qty_wines}}</p>
          <p id="registrationform">Geskep deur: {{form.created_by}}</p>
        {% endif %}
        {% if closing %}
          <p id="registrationform">Sluit wynproe: {{form.close_tasting}}</p>
        {% endif %}
        <hr>
        <input type="submit" class="btn btn-warning glyphicon glyphicon-plus" value=" Laai Wynproe">
      </form>
      <p></p>
        <button onclick="goBack()" class="btn btn-primary glyphicon glyphicon-step-backward"> Terug</button>
    </div>
  </div>
  <script>
    function goBack(){
      window.history.back();
    }
  </script>
  <script src="{% static "JS/tasting.js" %}"></script>
  {% endblock %}

klubvino/winetasting/templates/winetasting/winetasting_page.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <button onclick="window.location='{% url 'winetasting:create_tasting' %}'"type="button" class="btn btn-warning glyphicon glyphicon-plus event"> Nuwe</button>
    <div class="row">
      {% include 'winetasting/_tasting_entry.html' %}
    </div>
  </div>
  <script src="{% static "JS/tasting.js" %}"></script>
  {% endblock %}

klubvino/winetasting/templates/winetasting/winetastinginfo_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% load widget_tweaks %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <p id="id_date">Datum: {{form.date}}</p>
        <p id="registrationform">Kultivar: {{form.cultivar}}</p>
        <p id="registrationform">Kubernaam: {{form.username}}</p>
        <p id="registrationform">Kode: {{form.wine_code_name}}</p>
        <p id="registrationform">Punt: {{form.points}}</p>
        <p id="registrationform">Kommentaar:</p>
        {{form.comments|add_class:"form-control"}}
        <p></p>
        <input type="submit" class="btn btn-warning glyphicon glyphicon-plus" value=" Laai Wyn">
      </form>
      <p></p>
      <button onclick="goBack()" class="btn btn-primary glyphicon glyphicon-step-backward"> Terug</button>
    </div>
  </div>
  <script>
    function goBack(){
      window.history.back();
    }
  </script>
  <script>
    $(document).ready(function(){
      $("#id_date").hide();
    });
  </script>
  <script src="{% static "JS/tasting.js" %}"></script>
  {% endblock %}

klubvino/winetasting/templates/winetasting/winetastingresults_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <p id="registrationform">Datum: {{form.relative_date}}</p>
        <p id="registrationform">Kultivar: {{form.cultivar}}</p>
        <p id="registrationform">Kode: {{form.wine_code_name}}</p>
        <p id="registrationform">Kiekie: {{form.pics}}</p>
        <p id="registrationform">Regte Naam: {{form.real_name}}</p>
        <p id="registrationform">Kelder: {{form.cellar}}</p>
        <p id="registrationform">Jaar: {{form.year}}</p>
        <p id="registrationform">Prys: {{form.price}}</p>
        <p id="registrationform">Punt: {{form.total}}</p>
        <hr>
        <input type="submit" class="btn btn-warning glyphicon glyphicon-plus" value=" Laai Wyn">
      </form>
      <p></p>
      <button onclick="goBack()" class="btn btn-primary glyphicon glyphicon-step-backward"> Terug</button>
    </div>
  </div>
  <script>
    function goBack(){
      window.history.back();
    }
  </script>
  <script src="{% static "JS/tasting.js" %}"></script>
  {% endblock %}