klubvino/chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('chat', views.ChatView.as_view(), name='chat'),
]

klubvino/klubvino/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views
from klubvino import settings

urlpatterns = [
    path('bestuur/admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('wineinfo/', include('wineinfo.urls', namespace='wineinfo')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('search/', include('search.urls', namespace='search')),
    path('events/', include('event_calendar.urls', namespace='event_calendar')),
    path('tasting/', include('winetasting.urls', namespace='winetasting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

klubvino/wineinfo/urls.py
from django.urls import path
from wineinfo import views

app_name = 'wineinfo'

urlpatterns = [
    path('cultivar/', views.CultivarView.as_view(), name='cultivar'),
    path('cultivar/<int:pk>', views.WynInfoView.as_view(), name='detail'),
    path('create/', views.CultivarCreateView.as_view(), name='create'),
    path('create_wine/', views.WineCreateView.as_view(), name='create_wine'),
    path('update_wine/<int:pk>', views.WineUpdateView.as_view(), name='update_wine'),
    path('delete_wine/<int:pk>', views.WineDeleteView.as_view(), name='delete_wine'),
]

klubvino/wineinfo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Cultivar(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("wineinfo:cultivar")

    class Meta:
        ordering = ('name',)


class WineInfo(models.Model):
    cultivar = models.ForeignKey(Cultivar, related_name='wine', on_delete=models.CASCADE)
    pics = models.ImageField(upload_to='wine_pics', blank=True, null=True)
    name = models.CharField(max_length=256)
    cellar = models.CharField(max_length=256)
    year = models.IntegerField()
    price = models.CharField(max_length=256)
    rating = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("wineinfo:cultivar")

klubvino/wineinfo/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from . import models
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

# Create your views here.
## Cultivar views
class CultivarView(ListView):
    context_object_name = 'cultivars'
    model = models.Cultivar

class CultivarCreateView(CreateView):
    fields = ('name',)
    model = models.Cultivar

## Wine info views
class WynInfoView(DetailView):
    context_object_name = 'wyn_goed'
    model = models.Cultivar
    template_name = 'wineinfo/wyn_detail.html'

class WineCreateView(CreateView):
    fields = "__all__"
    model = models.WineInfo

class WineUpdateView(UpdateView):
    fields = "__all__"
    model = models.WineInfo

class WineDeleteView(DeleteView):
    model = models.WineInfo
    success_url = reverse_lazy('wineinfo:cultivar')

klubvino/wineinfo/templates/wineinfo/cultivar_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h2>{% if not form.instance.pk %}
            Voeg 'n kultivar by:
          {% else %}
            Verander 'n kultivar:
          {% endif %}
      </h2>
      <form method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p}} -->
        <p id="registrationform">Naam: {{form.name}}</p>
        <input type="submit" class="btn btn-warning glyphicon glyphicon-step-backward" value="Laai Kultivar">
        <a href="{% url 'wineinfo:cultivar' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Kanselleer</a>
      </form>
    </div>
  </div>
  <script src="{% static "JS/wyninfo.js" %}"></script>
  {% endblock %}

klubvino/wineinfo/templates/wineinfo/cultivar_list.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <ol class="cultivar_list">
        {% for wyn in cultivars %}
          <h4><li><a href="{{wyn.id}}">{{ wyn.name }}</a></li></h4>
        {% endfor %}
      </ol>
      <a href="{% url 'wineinfo:create' %}" class="btn btn-warning glyphicon glyphicon-plus" role="button"> Nuwe Kultivar</a>
    </div>
  </div>
  <script src="{% static "JS/wyninfo.js" %}"></script>
  {% endblock %}

klubvino/wineinfo/templates/wineinfo/wineinfo_confirm_delete.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h2>Wyninligting</h2>
      <h2>Verwyder {{wineinfo.name}} - {{wineinfo.cellar}} van lys?:</h2>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Verwyder">
        <a href="{% url 'wineinfo:cultivar' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Kanselleer</a>
      </form>
    </div>
  </div>
  <script src="{% static "JS/wyninfo.js" %}"></script>
  {% endblock %}

klubvino/wineinfo/templates/wineinfo/wineinfo_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h2>Voeg 'n wyn by:</h2>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <p id="registrationform">Kultivar: {{form.cultivar}}</p>
        <p id="registrationform">Kiekie: {{form.pics}}</p>
        <p id="registrationform">Naam: {{form.name}}</p>
        <p id="registrationform">Kelder: {{form.cellar}}</p>
        <p id="registrationform">Jaar: {{form.year}}</p>
        <p id="registrationform">Prys: {{form.price}}</p>
        <p id="registrationform">Punt: {{form.rating}}</p>
        <input type="submit" class="btn btn-warning glyphicon glyphicon-plus" value=" Laai Wyn">
        <a href="{% url 'wineinfo:cultivar' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Kanselleer</a>
      </form>
    </div>
  </div>
  <script src="{% static "JS/wyninfo.js" %}"></script>
  {% endblock %}

klubvino/wineinfo/templates/wineinfo/wyn_detail.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      {% for wyne in wyn_goed.wine.all %}
        {% if wyne.pics%}
          <img src="{{ wyne.pics.url }}" alt="no image" width="200" height="300">
        {% else %}
          <p>Geen Kiekie!</p>
        {% endif %}
        <p id="registrationform">Kultivar: {{wyne.cultivar}}</p>
        <p id="registrationform">Naam: {{wyne.name}}</p>
        <p id="registrationform">Kelder: {{wyne.cellar}}</p>
        <p id="registrationform">Jaar: {{wyne.year}}</p>
        <p id="registrationform">Prys: {{wyne.price}}</p>
        <p id="registrationform">Punt: {{wyne.rating}}/10</p>
        <a href="{% url 'wineinfo:update_wine' pk=wyne.pk %}" class="btn btn-warning glyphicon glyphicon-edit" role="button"> Opdateer</a>
        <a href="{% url 'wineinfo:delete_wine' pk=wyne.pk %}" class="btn btn-danger glyphicon glyphicon-remove" role="button"> Verwyder</a>
        <p></p>
        <hr>
      {% endfor %}
      <a href="{% url 'wineinfo:create_wine' %}" class="btn btn-warning glyphicon glyphicon-plus" role="button"> Nuwe Wyn</a>
      <a href="{% url 'wineinfo:cultivar' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Terug</a>
    </div>
  </div>
  <script src="{% static "JS/wyninfo.js" %}"></script>
  {% endblock %}