klubvino/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('nuwelede', views.nuwelede, name='nuwelede'),
    path('lede/', views.UserListView.as_view(), name='user_list'),
    path('lede_update/<int:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('profile_update/<int:pk>', views.UserProfileInfoUpdateView.as_view(), name='profile_update'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

klubvino/chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('chat', views.ChatView.as_view(), name='chat'),
]

klubvino/klubvino/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views
from klubvino import settings

urlpatterns = [
    path('bestuur/admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('wineinfo/', include('wineinfo.urls', namespace='wineinfo')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('search/', include('search.urls', namespace='search')),
    path('events/', include('event_calendar.urls', namespace='event_calendar')),
    path('tasting/', include('winetasting.urls', namespace='winetasting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

klubvino/search/urls.py
from django.urls import path
from search import views

app_name = 'search'

urlpatterns = [
    path('search/', views.SearchView.as_view(), name='search'),
    path('search/<int:pk>', views.SearchDetailView.as_view(), name='search_detail')
]

klubvino/wineinfo/urls.py
from django.urls import path
from wineinfo import views

app_name = 'wineinfo'

urlpatterns = [
    path('cultivar/', views.CultivarView.as_view(), name='cultivar'),
    path('cultivar/<int:pk>', views.WynInfoView.as_view(), name='detail'),
    path('create/', views.CultivarCreateView.as_view(), name='create'),
    path('create_wine/', views.WineCreateView.as_view(), name='create_wine'),
    path('update_wine/<int:pk>', views.WineUpdateView.as_view(), name='update_wine'),
    path('delete_wine/<int:pk>', views.WineDeleteView.as_view(), name='delete_wine'),
]

klubvino/winetasting/urls.py
from django.urls import path
from winetasting import views

app_name = 'winetasting'

urlpatterns = [
    path('tasting/', views.TastingMainView.as_view(), name='tasting'),
    path('create_tasting/', views.TastingCreateView.as_view(), name='create_tasting'),
    path('update_tasting/<int:pk>', views.TastingUpdateView.as_view(), name='update_tasting'),
    path('tasting/<int:pk>', views.WineTastingDetailView.as_view(), name='detail'),
    path('mystery_wine/', views.MysteryWineCreateView.as_view(), name='mystery_wine'),
    path('mystery_update/<int:pk>', views.MysteryWineUpdateView.as_view(), name='mystery_update'),
    path('results/', views.ResultView.as_view(), name='results'),
    path('results/<int:pk>', views.ResultUpdateView.as_view(), name='result_update'),
]

klubvino/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "CSS/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "CSS/mystyle.css" %}">
    <script src="{% static "JS/jquery-3.3.1.js" %}"></script>
    <script src="{% static "JS/bootstrap.min.js" %}"></script>
    <title>VINO APP</title>
  </head>
  <body id="myBody" onload="" >
  <nav id="topnav" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="leftMenuItems" class="navbar-brand" href="{% url 'home' %}">KLUB-VINO</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          {% if user.is_authenticated %}
            <li id="ledeMenu"><a id="leftMenuItems" href="{% url 'accounts:user_list' %}">LEDE</a></li>
            <li id="kletsMenu"><a id="leftMenuItems" href="{% url 'chat:chat' %}">KLÊTS</a></li>
            <li id="gebeureMenu"><a id="leftMenuItems" href="{% url 'event_calendar:events' %}">GEBEURE</a></li>
            <li id="wynproeMenu"><a id="leftMenuItems" href="{% url 'winetasting:tasting' %}">WYNPROE</a></li>
            <li id="inligtingMenu"><a id="leftMenuItems" href="{% url 'wineinfo:cultivar' %}">WYNINLIGTING</a></li>
              {% if perms.auth.can_reg_usr %}
              <li id="registerMenu"><a id="leftMenuItems" href="{% url 'accounts:nuwelede' %}">REGISTREER</a></li>
              {% endif %}
              {% if perms.auth.add_permission %}
              <li id="registerMenu"><a id="leftMenuItems" href="{% url 'admin:index' %}">ADMIN</a></li>
              {% endif %}
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <div id="leftMenuItems" class="search-container">
              <form action="{% url 'search:search' %}" method="POST">
                {% csrf_token %}
                <input type="text" placeholder="Soek hier..." name="search">
                <!-- <button class="btn btn-warning glyphicon glyphicon-search" type="submit"></button> -->
              </form>
            </div>
          </li>
          <li><a id="leftMenuItems" href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          <li><a id="userID">{{ user }}</a>
          {% else %}
            <li id="tekenMenu"><a id="leftMenuItems" href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>
    <div class="container" style="margin-top:60px">
      {% block body_block %}
      <!-- Anything ouside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

klubvino/templates/index.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h2>Welkom Wyn-Vrinne!</h2>
      <h4>Hier sal jy al die wynverwante inligting van die wynproe-sessies vind.</h4>
      <h4>Jy sal van ons hoogsgeleërde en verspotte opinies oor die betrokke wyne kan lees.</h4>
      <h4>Teken asseblief in om die funksies van die kuberblad te kan gebruik.</h4>
    </div>
  </div>
  {% endblock %}